### ISSUE TITLE
Recorder cannot start

### ISSUE THREAD

**Issue by Aung-Myint-Thein** [hyochan/react-native-audio-recorder-player#237]
Our app is running fine on many users but one user reported that the app crash upon recording. When I check the log, I saw this stacktrace. 

```
java.lang.NullPointerException: println needs a message
    at android.util.Log.println_native(Log.java)
    at android.util.Log.d(Log.java:155)
    at com.dooboolab.RNAudioRecorderPlayerModule.stopRecorder(RNAudioRecorderPlayerModule.java:167)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:228)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:919)
```

And the log said this happened right after I stop the recording because the recorder start failed:

```
Error: start failed.
arguments: [{"nativeStackAndroid":[],"userInfo":null,"message":"start failed.","code":"startRecord"}]
logger: console
```

### Version of react-native-audio-recorder-player
2.5.3

### Platforms you faced the error (IOS or Android or both?)
Android (Realme 6pro, Android 10)

### Expected behavior
Recording start.

### Actual behavior
Recording cannot start.

Have anyone faced this issue before? Suggestions and ideas are appreciated. Thanks!

**Comment by nhinovaio** [comment]
Here is the same

**Comment by yasirwahid** [comment]
has anyone resolved it? i am getting the same issue

**Comment by hsavit1** [comment]
same issue

**Comment by soheilaGhayour** [comment]
Facing same issue on Android 10

**Comment by savioseb** [comment]
From my experience this error seems to be happening when the recorder is not stopped properly in the previous run. If the recorder is stopped properly, this error doesn't occur for me.

**Comment by hyochan** [comment]
Could you follow the [TIPS in readme](https://github.com/hyochan/react-native-audio-recorder-player#tips) and see if it resolves? Also please check out the `Example` project.

Closes for now until new feedback

**Comment by ghsa** [comment]
I was with the same error, after edit `RNAudioRecorderPlayerModule.java` and comment `Log.d(TAG, stopException.getMessage());`, I discovered that the problem was really android permission, but I already had asked for `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` permissons.

I fixed this adding `  <application android:requestLegacyExternalStorage="true"....` to AndroidManifest
