### ISSUE TITLE
Stop Failed

### ISSUE THREAD

**Issue by Erenner** [hyochan/react-native-audio-recorder-player#490]
`
Error: stop failed.
    at Object.promiseMethodWrapper [as stopRecorder] (NativeModules.js:106:51)
    at AudioRecorderPlayer.<anonymous> (index.ts:290:36)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:16)
    at _next (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at tryCallTwo (core.js:45:5)
    at doResolve (core.js:200:13)
    at new Promise (core.js:66:3)
    at AudioRecorderPlayer.stopRecorder (asyncToGenerator.js:21:12)
`
### Version of react-native-audio-recorder-player
^3.5.1"

### Version of React Native
68

### Platforms you faced the error (IOS or Android or both?)
Android on mac 1

**Comment by steffenkleinle** [comment]
We have the same problem. Did you find any solution to fix this? Some more information:
This seems to happen if the recorder is directly stopped after starting the recording, i.e. not holding the recording button.

https://user-images.githubusercontent.com/29095487/203602109-9a10da0d-f08a-4cb7-8575-95263176e49f.mp4

**Comment by hyochan** [comment]
Could you try adding `requestLegacyExternalStorage = "true"` on `AndroidManifest.xml`?

Related to https://github.com/react-native-cameraroll/react-native-cameraroll/issues/192#issuecomment-679122972

**Comment by Erenner** [comment]
> Could you try adding `requestLegacyExternalStorage = "true"` on `AndroidManifest.xml`?
> 
> Related to [react-native-cameraroll/react-native-cameraroll#192 (comment)](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/192#issuecomment-679122972)

I tried but it didn't work

**Comment by jibo001** [comment]
same issue

**Comment by steffenkleinle** [comment]
We worked around this now with keeping track of the recording time and using a timeout to stop the recording if too little time has passed (<100ms):
``` tsx
  const [recordingTime, setRecordingTime] = useState<number>(0)

  const onStopRecording = async (): Promise<void> => {
    audioRecorderPlayer.removeRecordBackListener()
    if (recordingTime < minRecordingTime) {
      // If the button is just tapped and the recording is stopped to fast, an error is thrown from which it is not possible to recover
      // https://github.com/hyochan/react-native-audio-recorder-player/issues/490
      setTimeout(() => {
        audioRecorderPlayer.stopRecorder().catch(reportError)
      }, minRecordingTime)
      return
    }
    try {
      const recordingPath = await audioRecorderPlayer.stopRecorder()
      if (recordingPath.includes('file://')) {
        onAudioRecorded(recordingPath)
      }
    } catch (e) {
      // do something with errors
    }
  }

  const onStartRecording = async (): Promise<void> => {
    if (recordingTime !== 0) {
      return
    }
    try {
      await audioRecorderPlayer.startRecorder(undefined, undefined, true)
      audioRecorderPlayer.addRecordBackListener(async e => {
        setRecordingTime(e.currentPosition)
        if (e.currentPosition > maxRecordingTime) {
          await onStopRecording()
        }
      })
    } catch (error) {
      // do something with errors
    }
```

**Comment by hyochan** [comment]
Hi — closing this as `🗑 stale-legacy`. This issue references the pre-Nitro `react-native-audio-recorder-player` API, which has since been rewritten on top of [react-native-nitro-modules](https://github.com/mrousavy/nitro) and republished as `react-native-nitro-sound`. The internals, method names, and error surfaces are different.

If this still reproduces on the **current `react-native-nitro-sound`**, please open a fresh issue with:
- `react-native-nitro-sound` version
- React Native version
- Platform (iOS/Android) + OS version
- A minimal reproduction

We'll triage it promptly. Thanks for your patience. 🙏

> 🤖 This repo is now AI-native maintained — see [#787](https://github.com/hyochan/react-native-nitro-sound/discussions/787).
