### ISSUE TITLE
Build Issues with latest template 

### ISSUE THREAD

**Issue by sikemullivan** [hyochan/react-native-audio-recorder-player#494]
### Version of react-native-audio-recorder-player
3.5.1

### Version of React Native
0.70.4

### Platforms you faced the error (IOS or Android or both?)
both

### Expected behavior
It should build.

### Actual behavior
Build errors

### Steps to reproduce the behavior
- Create new React Native Typescript Project
`npx react-native init AwesomeTSProject --template react-native-template-typescript`
- Follow this projects installation steps
- Observe build errors on both Android and iOS

Android - compile is no longer a key word in the latest versions of Gradle
```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/me/repos/myproject/play/android/app/build.gradle' line: 280

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method compile() for arguments [project ':react-native-audio-recorder-player'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
iOS - The instructions are not very clear on setting up Swift integration. I added a Swift file to the project and observed the Bridge Header section appearing. Beyond that, it's not clear what I should do.

Building from xcode
`/Users/me/repos/myproject/play/node_modules/react-native-audio-recorder-player/ios/RNAudioRecorderPlayer.m:1:9 'React/RCTBridgeModule.h' file not found
`
Build via npx react-native run-ios
```
The following build commands failed:
        CompileC /Users/me/Library/Developer/Xcode/DerivedData/play-ccgvajhxuglhdcadgflolrdinceb/Build/Intermediates.noindex/RNAudioRecorderPlayer.build/Debug-iphonesimulator/RNAudioRecorderPlayer.build/Objects-normal/x86_64/RNAudioRecorderPlayer.o /Users/me/repos/myproject/play/node_modules/react-native-audio-recorder-player/ios/RNAudioRecorderPlayer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNAudioRecorderPlayer' from project 'RNAudioRecorderPlayer')
(1 failure)
```

**Comment by sikemullivan** [comment]
For iOS, the installation is much easier than the provided instructions. All you need to do is add a Swift file to the project in XCode. No need to link the the project.

**Comment by sikemullivan** [comment]
For Android, step #3 should use implementation and not compile. Compile has been removed from gradle. 

3. Insert the following lines inside the dependencies block in android/app/build.gradle:

```
  // compile project(':react-native-audio-recorder-player')
  implementation project(':react-native-audio-recorder-player')
```

**Comment by hyochan** [comment]
Thanks for sharing your problem @sikemullivan .

The manual installation is a pretty old approach which is for users using React Native version below 0.60. Mostly, automatic installation and [post installation](https://github.com/hyochan/react-native-audio-recorder-player#post-installation) is what you need.

**Comment by Srijan67** [comment]
I tried what you suggested @sikemullivan but still for it it is throwing same error, 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 executed

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'E:\Projects\Syscorp\node_modules\react-native-audio-recorder-player\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-audio-recorder-player'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-audio-recorder-player'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s


This is my android/app/build.gradle file dependencies: 
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])

    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    implementation project(':react-native-audio-recorder-player')
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.fbjni'
    }

**Comment by pradipbhanderi** [comment]
i have same problem

**Comment by hyochan** [comment]
Could anyone please try the [example project](https://github.com/hyochan/react-native-audio-recorder-player/tree/main/Example) which also has the latest build?

**Comment by jforaker** [comment]
Can confirm adding this package breaks Android on a fresh `init` of the current react-native architecture (0.71.4) 

```
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/me/dev/rntester/app/node_modules/react-native-audio-recorder-player/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-audio-recorder-player'.
> Plugin with id 'kotlin-android' not found.

```

**Comment by hectorleiva** [comment]
@jforaker 

This workaround (https://github.com/react-native-webview/react-native-webview/issues/1407#issuecomment-634436481) seems to have helped in at least getting my RN Project compiling properly for Android:

`package.json`
```
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-audio-recorder-player": "^3.5.3",
```

`android/build.gradle`
```
buildscript {
    repositories {
        // adding google() here to update to gradle 3
        google()
        mavenCentral()
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath('com.android.tools.build:gradle:7.3.1')
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31")
    }
}
```

Adding the following in `android/build.gradle` seems to be key.
The version of `kotlin-gradle-plugin` was one that CoPilot recommended and it works for me at the moment.
```
classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31")
```

**Comment by gsudhanshu** [comment]
@hyochan I am facing build issues in iOS

react native 0.71.1
RNAudioRecorderPlayer 3.5.3

error: underlying Objective-C module 'RNAudioRecorderPlayer' not found

**Comment by pulkitk702** [comment]
info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\Projects\CritiComm\criticomm\android\settings.gradle' line: 8

* What went wrong:
A problem occurred evaluating settings 'CritiComm'.
> Cannot convert string value '../node_modules/react-native-audio-recorder-player/android' to an enum value of type 'org.gradle.api.PathValidation' (valid case insensitive values: NONE, EXISTS, FILE, DIRECTORY)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\Projects\CritiComm\criticomm\android\settings.gradle' line: 8

* What went wrong:
A problem occurred evaluating settings 'CritiComm'.
> Cannot convert string value '../node_modules/react-native-audio-recorder-player/android' to an enum value of type 'org.gradle.api.PathValidation' (valid case insensitive values: NONE, EXISTS, FILE, DIRECTORY)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
i am also facing the same issue can anyone find the solution ??

**Comment by puniker** [comment]
> For Android, Step 1 can be removed and Step 3 should use implementation and not compile. Compile has been removed from gradle.
> 
> 3. Insert the following lines inside the dependencies block in android/app/build.gradle:
> 
> ```
>   implementation project(':react-native-audio-recorder-player')
> ```


This has worked for me! Thanks!

**Comment by hyochan** [comment]
Hi — closing this as `🗑 stale-legacy`. This issue references the pre-Nitro `react-native-audio-recorder-player` API, which has since been rewritten on top of [react-native-nitro-modules](https://github.com/mrousavy/nitro) and republished as `react-native-nitro-sound`. The internals, method names, and error surfaces are different.

If this still reproduces on the **current `react-native-nitro-sound`**, please open a fresh issue with:
- `react-native-nitro-sound` version
- React Native version
- Platform (iOS/Android) + OS version
- A minimal reproduction

We'll triage it promptly. Thanks for your patience. 🙏

> 🤖 This repo is now AI-native maintained — see [#787](https://github.com/hyochan/react-native-nitro-sound/discussions/787).
