### ISSUE TITLE
build faliure 

### ISSUE THREAD

**Issue by pulkitk702** [hyochan/react-native-audio-recorder-player#539]
info JS server already running.
info Installing the app...
5 actionable tasks: 5 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\Projects\CritiComm\criticomm\node_modules\react-native-audio-recorder-player\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-audio-recorder-player'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-audio-recorder-player'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\Projects\CritiComm\criticomm\node_modules\react-native-audio-recorder-player\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-audio-recorder-player'.
> Plugin with id 'kotlin-android' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-audio-recorder-player'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at makeError (D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (D:\Projects\CritiComm\criticomm\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
i just install the dependecies and try to run it but the build got failed can anybody tell me ??

**Comment by hyochan** [comment]
Hi — closing this as `🗑 stale-legacy`. This issue references the pre-Nitro `react-native-audio-recorder-player` API, which has since been rewritten on top of [react-native-nitro-modules](https://github.com/mrousavy/nitro) and republished as `react-native-nitro-sound`. The internals, method names, and error surfaces are different.

If this still reproduces on the **current `react-native-nitro-sound`**, please open a fresh issue with:
- `react-native-nitro-sound` version
- React Native version
- Platform (iOS/Android) + OS version
- A minimal reproduction

We'll triage it promptly. Thanks for your patience. 🙏

> 🤖 This repo is now AI-native maintained — see [#787](https://github.com/hyochan/react-native-nitro-sound/discussions/787).
